language: android
android:
  components:
  - platform-tools
  - tools
  - build-tools-22.0.0
  - android-22
sudo: false
cache:
    directories:
        - node_modules
        - bower_components
install:
- echo "Install stage"
- sed -i -e "s/\$VERSIONCODE/$TRAVIS_BUILD_NUMBER/g" config.xml
- sed -i -e "s/\$VERSIONCODE/$TRAVIS_BUILD_NUMBER/g" package.json
- npm install
- export PATH=$(npm bin):$PATH
- bower install
before_script:
- echo "Before script stage"
script:
- echo "Script stage"
- grunt build
- ionic platform add android
- ionic resources --splash
- ionic resources --icon
- ionic build --release android
after_success:
- export PATH=$(find /usr/local/android-sdk/ -name zipalign -type f| head -1 | sed -e 's/\/zipalign//g'):$PATH
- zipalign -v 4 platforms/android/ant-build/DCUTT-release-unsigned.apk platforms/android/ant-build/DCUTT.apk
after_failure:
- echo "After failure stage"
after_script:
- echo "After script stage"
