language: android
android:
  components:
  - platform-tools
  - tools
  - build-tools-22.0.0
  - android-22
sudo: false
cache:
  directories:
  - node_modules
  - bower_components
install:
- echo "Install stage"
- export PATH=.bin:$(npm bin):$(find /usr/local/android-sdk/ -name zipalign -type
  f| head -1 | sed -e 's/\/zipalign//g'):$PATH
- set-version.sh $TRAVIS_BUILD_NUMBER
- npm install
- bower install
before_script:
- echo "Before script stage"
script:
- echo "Script stage"
- build-android.sh
after_success:
- sign-apk.sh "release-key.keystore" "dcutt" "$STORE_PASSWORD" DCUTT-$TRAVIS_BUILD_NUMBER.apk
after_failure:
- echo "After failure stage"
after_script:
- echo "After script stage"
env:
  global:
  - secure: bIsKBbVhTN8dOatgGD9mdQ3V+3zgQCVhuiCn2y2oX1IlTkG+ip1ORwRrzKF3yTdpwRbvr1ZZ04Y48pXdPVo9LNtsHukjBP1d/kxgYdRmjqvaioxe7hQ7NiLX7maU1qpbKuuzXSVJpUtXA9/GiMJnhM/xI6RdC20PnV+f7e5jQFg=
  - secure: RRPll+aVYDScUzxlIRXXkoDBJD0+VGfrLCe1bPzHYiu3UfrTu7Svv7HmlAKyNh73MA02WrF276viU5NaALoEvE6MzxlK6NoHZugV/GZdHBjNsnllAzUv5TnkxRg3pfJwTiwdGUBlrPZEZCy9En0wNln/tEtkdqZBxgC7wK57/B0=
deploy:
  provider: releases
  api_key:
    secure: BbCWl+zO+6OqXANeaZOWt5lc3qyHOnoQE0mKBEa7UNthhkqLTIT2ojnCHildDT2aWK17vRsUUeQR+A1L0PNWIrVq/rHq5+y/ZPfnMNIehC1tfWLhyBP+bufLwN6Gj9AyU3/n1egWlA0TjMjsUF4dnc6IgT1tw3aBC25DGvX6sV8=
  file: DCUTT-$TRAVIS_BUILD_NUMBER.apk
  on:
    tags: true
    all_branches: true
    repo: imduffy15/DCUTT-UI
