language: android
android:
  components:
  - platform-tools
  - tools
  - build-tools-22.0.0
  - android-22
sudo: false
cache:
  directories:
  - node_modules
  - bower_components
install:
- echo "Install stage"
- export PATH=.bin:$(npm bin):$(find /usr/local/android-sdk/ -name zipalign -type
  f| head -1 | sed -e 's/\/zipalign//g'):$PATH
- set-version.sh $TRAVIS_BUILD_NUMBER
- npm install
- bower install
before_script:
- echo "Before script stage"
- nvm install $NODE_VERSION
- nvm use $NODE_VERSION
script:
- echo "Script stage"
- build-android.sh
after_success:
- push-release.sh
- sign-apk.sh "release-key.keystore" "dcutt" "$STORE_PASSWORD" "DCUTT-$TRAVIS_BUILD_NUMBER.apk"
after_failure:
- echo "After failure stage"
after_script:
- echo "After script stage"
env:
  - NODE_VERSION="0.12"
  global:
  - secure: bIsKBbVhTN8dOatgGD9mdQ3V+3zgQCVhuiCn2y2oX1IlTkG+ip1ORwRrzKF3yTdpwRbvr1ZZ04Y48pXdPVo9LNtsHukjBP1d/kxgYdRmjqvaioxe7hQ7NiLX7maU1qpbKuuzXSVJpUtXA9/GiMJnhM/xI6RdC20PnV+f7e5jQFg=
  - secure: IWLRBWNx1qjaYI2ux0ZK8m5hSeaawgY1+WaJ6sPqHg+EkUnVevKZv2BW1lOFmT1am7MG+E4gMLmAy7Sq5ltk0pfDh4KWlxhiILVh1nNu4tzaVKVRlIeO5LUhYizC9xy1edfriKeNZTSX64oymmGArL2BYR3wCZjnzu24KFTimsM=
deploy:
  provider: releases
  api_key:
    secure: kWuX1zaujpG/gcqBlXkAAN2LpEWMk9npzQd63VLuWNqFuhxyw2GYi7Wm6gwXkso6wM77iOH8mY+HUUuZglvB7KePgeL60pZOAO/szjQBaDexn/28N/nGFYOlKefYrnSPAX7fXcxcvjQayUCoZNDE/YJaS9iZ/zIKuwKAYNlpUIc=
  file: DCUTT-$TRAVIS_BUILD_NUMBER.apk
  on:
    tags: true
    all_branches: true
    repo: imduffy15/DCUTT-UI
