language: android
android:
  components:
  - platform-tools
  - tools
  - build-tools-22.0.0
  - android-22
sudo: false
cache:
  directories:
  - node_modules
  - bower_components
install:
- echo "Install stage"
- export PATH=.bin:$(npm bin):$(find /usr/local/android-sdk/ -name zipalign -type f| head -1 | sed -e 's/\/zipalign//g'):$PATH
- set-version.sh $TRAVIS_BUILD_NUMBER
- npm install
- bower install
before_script:
- echo "Before script stage"
script:
- echo "Script stage"
- build-android.sh
after_success:
- sign-apk.sh "release-key.keystore" "dcutt" "$STORE_PASSWORD" release.apk
after_failure:
- echo "After failure stage"
after_script:
- echo "After script stage"
env:
  global:
    secure: bIsKBbVhTN8dOatgGD9mdQ3V+3zgQCVhuiCn2y2oX1IlTkG+ip1ORwRrzKF3yTdpwRbvr1ZZ04Y48pXdPVo9LNtsHukjBP1d/kxgYdRmjqvaioxe7hQ7NiLX7maU1qpbKuuzXSVJpUtXA9/GiMJnhM/xI6RdC20PnV+f7e5jQFg=
